# Generated by Django 5.1 on 2024-08-29 10:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('suppliers', '0002_suppliers_updated_at_alter_suppliers_created_at'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='suppliers',
            options={'ordering': ['name'], 'verbose_name': 'Fornecedor'},
        ),
    ]
