# Generated by Django 5.1 on 2024-08-29 10:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('outflows', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='outflow',
            options={'ordering': ['-created_at'], 'verbose_name': 'Saída'},
        ),
    ]
