# Generated by Django 5.1 on 2024-08-23 20:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inflows', '0001_initial'),
        ('products', '0001_initial'),
        ('suppliers', '0002_suppliers_updated_at_alter_suppliers_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='inflow',
            name='Product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='products.product', verbose_name='Produto'),
        ),
        migrations.AddField(
            model_name='inflow',
            name='supplier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='inflow', to='suppliers.suppliers', verbose_name='Fornecedor'),
        ),
    ]
